// sportsdata.io important things in the json.
//* scoreConfig set by sleeper/admin/commish
let scoreConfig = {
  "PassingYards": 20,
  "PassingAttempts": 0,
  "PassingCompletions": 0,
  "PassingYards": 20,
  "PassingTouchdowns": 4,
  "PassingInterceptions": -1,
  "PassingSacks": 0,
  "PassingSackYards": 0,
  "RushingAttempts": 0,
  "RushingYards": 10,
  "RushingTouchdowns": 6,
  "ReceivingTargets": 0,
  "Receptions": .5,
  "ReceivingYards": 10,
  "ReceivingTouchdowns": 6,
  "Fumbles": 0,
  "FumblesLost": -1,
  "TwoPointConversionAttempts": 0,
  "TwoPointConversionPasses": 2,
  "TwoPointConversionRuns": 2,
  "TwoPointConversionReceptions": 2,
  "TwoPointConversionReturns": 2,
  "SoloTackles": 1,
  "AssistedTackles": .5,
  "TacklesForLoss": 2,
  "Sacks": 2,
  "SackYards": 0,
  "PassesDefended": 1,
  "Safeties": 2,
  "FumblesForced": 1,
  "FumblesRecovered": 1,
  "FumbleReturnYards": 0,
  "FumbleReturnTouchdowns": 6,
  "Interceptions": 1,
  "InterceptionReturnYards": 0,
  "InterceptionReturnTouchdowns": 6,
  "PuntReturns": 0,
  "PuntReturnYards": 20,
  "PuntReturnTouchdowns": 6,
  "KickReturns": 0,
  "KickReturnYards": 20,
  "KickReturnTouchdowns": 6,
  "BlockedKicks": 1,
  "BlockedKickReturns": 0,
  "BlockedKickReturnYards": 0,
  "BlockedKickReturnTouchdowns": 6,
  "FieldGoalReturns": 0,
  "FieldGoalReturnYards": 20,
  "FieldGoalReturnTouchdowns": 6,
  "FieldGoalsAttempted": 0,
  "FieldGoalsMade": 3,
  "FieldGoalsYards": 0,
  "FieldGoalsHadBlocked": 0,
  "ExtraPointsAttempted": 0,
  "ExtraPointsMade": 1,
  "ExtraPointsHadBlocked": 0,
};

// Will load the above muliplier/math configuration so when it takes in the below information 
let scoringObject = {
  "PassingAttempts": scoreConfig.PassingAttempts,
  "PassingCompletions": scoreConfig.PassingCompletions,
  "PassingYards": scoreConfig.PassingYards,
  "PassingTouchdowns": scoreConfig.PassingTouchdowns,
  "PassingInterceptions": scoreConfig.PassingInterceptions,
  "PassingSacks": scoreConfig.PassingSacks,
  "PassingSackYards": scoreConfig.PassingSackYards,
  "RushingAttempts": scoreConfig.RushingAttempts,
  "RushingYards": scoreConfig.RushingYards,
  "RushingTouchdowns": scoreConfig.RushingTouchdowns,
  "ReceivingTargets": scoreConfig.ReceivingTargets,
  "Receptions": scoreConfig.Receptions,
  "ReceivingYards": scoreConfig.ReceivingYards,
  "ReceivingTouchdowns": scoreConfig.ReceivingTouchdowns,
  "Fumbles": scoreConfig.Fumbles,
  "FumblesLost": scoreConfig.FumblesLost,
  "TwoPointConversionAttempts": scoreConfig.TwoPointConversionAttempts,
  "TwoPointConversionPasses": scoreConfig.TwoPointConversionPasses,
  "TwoPointConversionRuns": scoreConfig.TwoPointConversionRuns,
  "TwoPointConversionReceptions": scoreConfig.TwoPointConversionReceptions,
  "TwoPointConversionReturns": scoreConfig.TwoPointConversionReturns,
  "SoloTackles": scoreConfig.SoloTackles,
  "AssistedTackles": scoreConfig.AssistedTackles,
  "TacklesForLoss": scoreConfig.TacklesForLoss,
  "Sacks": scoreConfig.Sacks,
  "SackYards": scoreConfig.SackYards,
  "PassesDefended": scoreConfig.PassesDefended,
  "Safeties": scoreConfig.Safeties,
  "FumblesForced": scoreConfig.FumblesForced,
  "FumblesRecovered": scoreConfig.FumblesRecovered,
  "FumbleReturnYards": scoreConfig.FumbleReturnYards,
  "FumbleReturnTouchdowns": scoreConfig.FumbleReturnTouchdowns,
  "Interceptions": scoreConfig.Interceptions,
  "InterceptionReturnYards": scoreConfig.InterceptionReturnYards,
  "InterceptionReturnTouchdowns": scoreConfig.InterceptionReturnTouchdowns,
  "PuntReturns": scoreConfig.PuntReturns,
  "PuntReturnYards": scoreConfig.PuntReturnYards,
  "PuntReturnTouchdowns": scoreConfig.PuntReturnTouchdowns,
  "KickReturns": scoreConfig.KickReturns,
  "KickReturnYards": scoreConfig.KickReturnYards,
  "KickReturnTouchdowns": scoreConfig.KickReturnTouchdowns,
  "BlockedKicks": scoreConfig.BlockedKicks,
  "BlockedKickReturns": scoreConfig.BlockedKickReturns,
  "BlockedKickReturnYards": scoreConfig.BlockedKickReturnYards,
  "BlockedKickReturnTouchdowns": scoreConfig.BlockedKickReturnTouchdowns,
  "FieldGoalReturns": scoreConfig.FieldGoalReturns,
  "FieldGoalReturnYards": scoreConfig.FieldGoalReturnYards,
  "FieldGoalReturnTouchdowns": scoreConfig.FieldGoalReturnTouchdowns,
  "FieldGoalsAttempted": scoreConfig.FieldGoalsAttempted,
  "FieldGoalsMade": scoreConfig.FieldGoalsMade,
  "FieldGoalsYards": scoreConfig.FieldGoalsYards,
  "FieldGoalsHadBlocked": scoreConfig.FieldGoalsHadBlocked,
  "ExtraPointsAttempted": scoreConfig.ExtraPointsAttempted,
  "ExtraPointsMade": scoreConfig.ExtraPointsMade,
  "ExtraPointsHadBlocked": scoreConfig.ExtraPointsHadBlocked
};




let playByPlay = {
  Plays: {
    "PlayID"              : 476166,
    "TimeRemainingMinutes": 15,
    "TimeRemainingSeconds": '00',
    "YardsToEndZone"      : 20,
    "Description"         : "San Francisco kicked off for 60 yards, Boston Scott returned kickoff for 29 yards",
    "YardsGained"         : 0,
    "IsScoringPlay"       : false,
    "ScoringPlay"         : null,
    "PlayerID"            : 1410,
    "Name"                : "Robbie Gould",
    "PlayStats"           : [
      {
        "PassingAttempts"             : scoreConfig.PassingAttempts,
        "PassingCompletions"          : scoreConfig.PassingCompletions,
        "PassingYards"                : scoreConfig.PassingYards,
        "PassingTouchdowns"           : scoreConfig.PassingTouchdowns,
        "PassingInterceptions"        : scoreConfig.PassingInterceptions,
        "PassingSacks"                : scoreConfig.PassingSacks,
        "PassingSackYards"            : scoreConfig.PassingSackYards,
        "RushingAttempts"             : scoreConfig.RushingAttempts,
        "RushingYards"                : scoreConfig.RushingYards,
        "RushingTouchdowns"           : scoreConfig.RushingTouchdowns,
        "ReceivingTargets"            : scoreConfig.ReceivingTargets,
        "Receptions"                  : scoreConfig.Receptions,
        "ReceivingYards"              : scoreConfig.ReceivingYards,
        "ReceivingTouchdowns"         : scoreConfig.ReceivingTouchdowns,
        "Fumbles"                     : scoreConfig.Fumbles,
        "FumblesLost"                 : scoreConfig.FumblesLost,
        "TwoPointConversionAttempts"  : scoreConfig.TwoPointConversionAttempts,
        "TwoPointConversionPasses"    : scoreConfig.TwoPointConversionPasses,
        "TwoPointConversionRuns"      : scoreConfig.TwoPointConversionRuns,
        "TwoPointConversionReceptions": scoreConfig.TwoPointConversionReceptions,
        "TwoPointConversionReturns"   : scoreConfig.TwoPointConversionReturns,
        "SoloTackles"                 : scoreConfig.SoloTackles,
        "AssistedTackles"             : scoreConfig.AssistedTackles,
        "TacklesForLoss"              : scoreConfig.TacklesForLoss,
        "Sacks"                       : scoreConfig.Sacks,
        "SackYards"                   : scoreConfig.SackYards,
        "PassesDefended"              : scoreConfig.PassesDefended,
        "Safeties"                    : scoreConfig.Safeties,
        "FumblesForced"               : scoreConfig.FumblesForced,
        "FumblesRecovered"            : scoreConfig.FumblesRecovered,
        "FumbleReturnYards"           : scoreConfig.FumbleReturnYards,
        "FumbleReturnTouchdowns"      : scoreConfig.FumbleReturnTouchdowns,
        "Interceptions"               : scoreConfig.Interceptions,
        "InterceptionReturnYards"     : scoreConfig.InterceptionReturnYards,
        "InterceptionReturnTouchdowns": scoreConfig.InterceptionReturnTouchdowns,
        "PuntReturns"                 : scoreConfig.PuntReturns,
        "PuntReturnYards"             : scoreConfig.PuntReturnYards,
        "PuntReturnTouchdowns"        : scoreConfig.PuntReturnTouchdowns,
        "KickReturns"                 : scoreConfig.KickReturns,
        "KickReturnYards"             : scoreConfig.KickReturnYards,
        "KickReturnTouchdowns"        : scoreConfig.KickReturnTouchdowns,
        "BlockedKicks"                : scoreConfig.BlockedKicks,
        "BlockedKickReturns"          : scoreConfig.BlockedKickReturns,
        "BlockedKickReturnYards"      : scoreConfig.BlockedKickReturnYards,
        "BlockedKickReturnTouchdowns" : scoreConfig.BlockedKickReturnTouchdowns,
        "FieldGoalReturns"            : scoreConfig.FieldGoalReturns,
        "FieldGoalReturnYards"        : scoreConfig.FieldGoalReturnYards,
        "FieldGoalReturnTouchdowns"   : scoreConfig.FieldGoalReturnTouchdowns,
        "FieldGoalsAttempted"         : scoreConfig.FieldGoalsAttempted,
        "FieldGoalsMade"              : scoreConfig.FieldGoalsMade,
        "FieldGoalsYards"             : scoreConfig.FieldGoalsYards,
        "FieldGoalsHadBlocked"        : scoreConfig.FieldGoalsHadBlocked,
        "ExtraPointsAttempted"        : scoreConfig.ExtraPointsAttempted,
        "ExtraPointsMade"             : scoreConfig.ExtraPointsMade,
        "ExtraPointsHadBlocked"       : scoreConfig.ExtraPointsHadBlocked
      }
    ]

  }
};



